require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CaseFilesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # CaseFile. As you add validations to CaseFile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      blob: nil
    }
  }

  let(:invalid_attributes) {
    {
      urn: 'xx'
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CaseFilesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all case_files as @case_files" do
      cf1 = CaseFile.create(blob: {'case' => {'date' => '20150213T1420', 'postcode' => 'RG2 7PU'} } )
      cf2 = CaseFile.create(blob: {'case' => {'date' => '20150213T1331', 'postcode' => 'SW10 9LB'} } )
      get :index, {}, valid_session
      expect(assigns(:case_files)).to eq([cf1, cf2])
      expect(response.body).to eq assigns(:case_files).to_json
    end
  end

  describe "GET #show" do
    it "assigns the requested case_file as @case_file" do
      skip
      case_file = CaseFile.create! valid_attributes
      get :show, {:id => case_file.to_param}, valid_session
      expect(assigns(:case_file)).to eq(case_file)
    end
  end

  describe "GET #new" do
    it "assigns a new case_file as @case_file" do
      get :new, {}, valid_session
      expect(assigns(:case_file)).to be_instance_of(CaseFile)
      expect(response.body).to eq assigns(:case_file).to_json
    end
  end

  describe "GET #edit" do
    it "assigns the requested case_file as @case_file" do
      skip
      case_file = CaseFile.create! valid_attributes
      get :edit, {:id => case_file.to_param}, valid_session
      expect(assigns(:case_file)).to eq(case_file)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new CaseFile" do
        skip
        expect {
          post :create, {:case_file => valid_attributes}, valid_session
        }.to change(CaseFile, :count).by(1)
      end

      it "assigns a newly created case_file as @case_file" do
        skip
        post :create, {:case_file => valid_attributes}, valid_session
        expect(assigns(:case_file)).to be_a(CaseFile)
        expect(assigns(:case_file)).to be_persisted
      end

      it "redirects to the created case_file" do
        skip
        post :create, {:case_file => valid_attributes}, valid_session
        expect(response).to redirect_to(CaseFile.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved case_file as @case_file" do
        skip
        post :create, {:case_file => invalid_attributes}, valid_session
        expect(assigns(:case_file)).to be_a_new(CaseFile)
      end

      it "re-renders the 'new' template" do
        skip
        post :create, {:case_file => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested case_file" do
        skip
        case_file = CaseFile.create! valid_attributes
        put :update, {:id => case_file.to_param, :case_file => new_attributes}, valid_session
        case_file.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested case_file as @case_file" do
        skip
        case_file = CaseFile.create! valid_attributes
        put :update, {:id => case_file.to_param, :case_file => valid_attributes}, valid_session
        expect(assigns(:case_file)).to eq(case_file)
      end

      it "redirects to the case_file" do
        skip
        case_file = CaseFile.create! valid_attributes
        put :update, {:id => case_file.to_param, :case_file => valid_attributes}, valid_session
        expect(response).to redirect_to(case_file)
      end
    end

    context "with invalid params" do
      it "assigns the case_file as @case_file" do
        skip
        case_file = CaseFile.create! valid_attributes
        put :update, {:id => case_file.to_param, :case_file => invalid_attributes}, valid_session
        expect(assigns(:case_file)).to eq(case_file)
      end

      it "re-renders the 'edit' template" do
        skip
        case_file = CaseFile.create! valid_attributes
        put :update, {:id => case_file.to_param, :case_file => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested case_file" do
      skip
      case_file = CaseFile.create! valid_attributes
      expect {
        delete :destroy, {:id => case_file.to_param}, valid_session
      }.to change(CaseFile, :count).by(-1)
    end

    it "redirects to the case_files list" do
      skip
      case_file = CaseFile.create! valid_attributes
      delete :destroy, {:id => case_file.to_param}, valid_session
      expect(response).to redirect_to(case_files_url)
    end
  end

end
